# Generated by Django 5.2 on 2025-05-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdata',
            name='light',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='oxidising',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='reducing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
