# Generated by Django 5.2 on 2025-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_plantdata_light_plantdata_oxidising_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('last_collection_time', models.DateTimeField(blank=True, null=True)),
                ('collection_duration', models.FloatField(default=0.0)),
                ('is_collecting_delayed', models.BooleanField(default=False)),
                ('status_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
